### ISSUE TITLE
File upload limitation

### ISSUE THREAD

**Issue by Qurus** [robmoorman/wagtailstreamforms#122]
I was checking on docs but did not see any information file upload field. Could you help me please how can I limit file upload size and file extensions limited?

**Comment by stuartaccent** [comment]
Hi @Qurus 

The max file size I usually handle within Django directly via the setting `FILE_UPLOAD_MAX_MEMORY_SIZE`, please see https://docs.djangoproject.com/en/2.2/ref/settings/#file-upload-max-memory-size.

Regards to the extension what I would prob do is to add a new field and set the `widget` to return something like:

```
widget = forms.FileInput(attrs={'accept':'application/pdf'})
```

ive not tested that at all but you can set the field and widget and all the option via https://wagtailstreamforms.readthedocs.io/en/latest/fields.html. You could also handle the content type too that way by creating your own field.

Hope that helps. Stu

**Comment by Qurus** [comment]
Thanks a lot for the explanation. Was really helpful.
